### ISSUE TITLE
Add a .stack/config.yaml

### ISSUE THREAD

**Issue by lwm** [lwm/dotfiles#1]
```
The following parameters were needed by the template but not provided: author-email, author-name, category, copyright, github-username
You can provide them in /home/lwm/.stack/config.yaml, like this:
templates:
  params:
    author-email: value
    author-name: value
    category: value
    copyright: value
    github-username: value
Or you can pass each one as parameters like this:
stack new new-template new-template -p "author-email:value" -p "author-name:value" -p "category:value" -p "copyright:value" -p "github-username:value"
```
